### ISSUE TITLE
Incorrect Path

### ISSUE THREAD

**Issue by hauer-io** [eshepelyuk/asciidoctor-plantuml-antora#3]
After running 'antora site.yml' my directory structure is:
├─ antora.yml
├─ build
│      ├─ _
│      │     ├── css
│      │       ├── font
│      │       ├── img
│      │       └── js
│      ├─ asciidoctor-plantuml-antora
│      │       └── index.html
│      └── index.html
├─ _images
│      └── 079bd6453a30089d164645a5c69ac134ff5062a9.png
├─ modules
│       └── ROOT
│                   ├── nav.adoc
│                   ├── pages
│                   └── index.adoc
└─ site.yml

Notice that the '_image' folder is next to the 'build' folder. But in the 'build/asciidoctor-plantuml-antora/index.html' the image is referenced as '\<img src="_images/079bd6453a30089d164645a5c69ac134ff5062a9.png" alt="diagram"\>'. So the '_image' folder should be within the 'build/asciidoctor-plantuml-antora' or the reference should be different.

This behaviour is the same for Version 1.0.3 and 2.0.0 of antora.

**Comment by eshepelyuk** [comment]
This is still not closed
https://github.com/eshepelyuk/asciidoctor-plantuml.js/issues/2

**Comment by eshepelyuk** [comment]
@hauer-io `1.0.2` is released with `Antora` support. This repo is updated as weel.

**Comment by hauer-io** [comment]
Thanks a lot. Works fine now.
